### ISSUE TITLE
Ch. 4: Cannot read property 'sort of undefined

### ISSUE THREAD

**Issue by wlbentley** [5t3ph/11ty-egghead-collection#1]
I'm getting the above message in my eleventy output (here's the full [gist](https://gist.github.com/wlbentley/aac4b453822cad9e6f4226cc8ed95755)) when trying to run the code from Chapter 4.

After receiving the error in my own code, following along your (great) tutorial, I tried copy/pasting the code from the repo. Same result.

Any ideas why `arr` is undefined here?

[Node V. 15.8.0, managed by asdf.]

package.json contents:
```
{
  "name": "eleventy-scratch",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "watch:sass": "sass --watch src/sass:public/css",
    "build:sass": "sass src/sass:public/css",
    "watch:eleventy": "eleventy --serve",
    "build-eleventy": "eleventy",
    "start": "npm-run-all build:sass --parallel watch:*",
    "build": "npm-run-all build:*"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@11ty/eleventy": "^0.11.1",
    "npm-run-all": "^4.1.5",
    "sass": "^1.32.8"
  }
}
```

Thx.

**Comment by 5t3ph** [comment]
Hi @wlbentley - I just pulled down the source files from this repo to run and double-check and did not receive an error. Double check what you listed for the `tags` in the blog data directory file vs. what you listed when going to access the collection. I myself sometimes pluralize the tag in one place but not the other which causes that type of error :) The error is saying that it isn't receiving an array so that's my best guess.

**Comment by wlbentley** [comment]
That was it. Thank you. :D

**Comment by wlbentley** [comment]
Issue resolved. Thanks so much.

**Comment by 5t3ph** [comment]
@wlbentley glad to hear it, thanks for reporting back!
